### ISSUE TITLE
Prediction/Extrapolation for CoxPHFitter(baseline_estimation_method='spline') not working

### ISSUE THREAD

**Issue by SurajitTest** [CamDavidsonPilon/lifelines#1032]
Using  CoxPHFitter(baseline_estimation_method='spline') and for censored observations, I am experiencing the given below:

1 : All survival probability values are equal to 1.
2 : All Median Lifetime values are equal to inf.
3 : All Expected Lifetime values are equal to 51.    
4 : All Cumulative Hazard values are equal to is 0.

The dataset used for analysis is from the lifelines package : from lifelines.datasets import load_rossi

**Comment by CamDavidsonPilon** [comment]
The problem is that when we call the spline method, we return a fixed array at specified times. So if a user wants to extrapolate beyond the largest time (or inbetween times), they see a constant value. When a user passes in `timeline` to a `predict` method, it should perform a "smarter" prediction. 

One solution is to return a function instead of a fixed array, and this function is used for all prediction. 

Will have to be fixed for a future release.
