### ISSUE TITLE
Dataframe of the survival function (cph.predict_survival_function())

### ISSUE THREAD

**Issue by jlim13** [CamDavidsonPilon/lifelines#1040]
Hello,

The output of this is an NxD dataframe. Each column appears to correspond to the row index of the data and the row is the probability of survival. So surivial_df[i, j] is the probability of the jth datapoint surviving after i units of time. Why do the row values skip values? For example, my first row value is 47.0 and the second jumps to 128.0. Why does it not start from 1 and increase by 1 unit of time?

**Comment by CamDavidsonPilon** [comment]
It's a good question. Because you are using a semi-parametric estimator, specifically the baseline-hazard is non-parametric. The baseline-hazard (and hence the baseline-survival) only has "information" to change at times observed in the dataset (if you sort your observations, you'll see `..., 47, 128, ...`). 

You can "fill-in" the gaps using the `timeline` argument in the `predict_survival_function` to create a custom timeline to evaluate against.

**Comment by jlim13** [comment]
I see, thanks for the insight! 

Doing something like this worked for me
```
survival_func_cph = cph.predict_survival_function(censored_X, 
   conditional_after=censored_subjects_last_obs, times = range(100) )
```
