### ISSUE TITLE
Predicting the survival function for uncensored test data? 

### ISSUE THREAD

**Issue by jlim13** [CamDavidsonPilon/lifelines#1058]
When we predict the survival function for a given data point (this data point is in my **test** set and is **uncensored**), do we use the `conditional_after` argument? To me, it doesn't make sense to because when I evaluate, I will take the median percentile as the predicted duration and measure that to the ground truth duration. The predicted duration shouldn't be dependent on the ground truth duration, correct? Or am I thinking about this wrong?

**Comment by CamDavidsonPilon** [comment]
> When we predict the survival function for a given data point (this data point is in my test set and is uncensored), do we use the conditional_after argument?

For uncensored subjects, `conditional_after` should be set to 0 (or not used at all). `conditional_after` was implemented for prediction of censored subjects. 

I'm wondering if there are docs that don't make this clear / are confusing?

**Comment by jlim13** [comment]
Thanks for the prompt reply! So, the docs don't directly say to set `conditional_after = 0` when predicting uncensored data. I just quickly looked through the docs just now, so I could have missed it!. I wouldn't say they are confusing, but the docs don't address the various questions surrounding the topic of evaluating on censored data. For example, I want to get a sense of how close my model can predict the actual duration in days. To evaluate this, I would have to get the L1-Loss for my predictions on the uncensored data in my test set and their ground truth durations. Maybe a section about doing this type of evaluation of uncensored data would make it clear to not use `conditional_after` on uncensored subjects? Thoughts?

**Comment by CamDavidsonPilon** [comment]
Yup, some related questions have come up on gitter, so I agree there's a need for better docs on this.

**Comment by konradsemsch** [comment]
Hi @CamDavidsonPilon! Sorry for reopening, but I was having similar issues when it comes to evaluation of my model on train/ test data, as well as the appropriate usage of `conditional_after` in that process. Let me explain:

In our projects we're seeking to predict customer churn. We have a starting hypothesis that the mean predicted lifetime should have a particular, linear relationship with the explanatory variable. At least such a relationship is observable when looking at the non-censored data lifetime value (duration from contract start to contract end). As a side note, the level of censoring is around 60%.

After training the model I would like to evaluate if model's predicted expectations (using `predict_expectation`) on the train/ test data, line up with our initial hypothesis. Here a couple of questions come up with:

- should I interpret the result `predict_expectation` using `conditional_after` on censored data as the "additional lifetime on top of their current lifetime" or "total lifetime including their current lifetime"?
- running `predict_expectation` on censored data without using `conditional_after` produces expected lifetimes as if such customers have in fact churned already correct? As such, these estimations are not really correct?
- in evaluating predictions on a test set where I have both censored and uncensored observations mixed together, I should run the `predict_expectation` function without `conditional_after` on the non-censored observations, and with `conditional_after` on the censored ones, correct?
- and a bit of side question to that: when forming my train and test sets, should I ensure similarly to typical classification problems, so that my target variable (churn) be balanced across these sets? Or should the test set include only the non-censored observations to truly evaluate my predictions? As long as I really like the comprehensive documentation of the package, I'm missing a little bit more details on evaluating if the predicted expected lifetimes are truly correct. Some more insights into best practices of that would be great

**Comment by CamDavidsonPilon** [comment]
@konradsemsch I think this is a good discussion for the [Discussions](https://github.com/CamDavidsonPilon/lifelines/discussions) forum! Do you mind moving this there?

**Comment by konradsemsch** [comment]
Agreed! doing right now 😉
