### ISSUE TITLE
How to run a two sample logrank test with left-censored data

### ISSUE THREAD

**Issue by mikekoss** [CamDavidsonPilon/lifelines#1117]
I am trying to use this software for a project with astronomy where some of the data is left-censored.  I can calculate the median (which I do with km.fit and left_censorship=True), then median=(kmf.cumulative_density_ <= 0.5).idxmin(0).

Now I want to do is compare two different populations with left censorship using the logrank (or other) test to determine the probability they are drawn from the same distribution.  Is this possible?  It doesn't seem like left_censorship=True works with logrank.

**Comment by CamDavidsonPilon** [comment]
I can think of two ideas, but both are not out-of-the-box ready for your application (this gives me motivation though!)

1. Use a survival-difference-at-time test. This is a good successor of the log-rank test, see more information [here](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/1471-2288-13-152#Sec27). As far as I know, this can handle left censored data since it is only testing the survival function at a specific time. In *lifelines*, I have this implemented _but_ don't have support to handle left censored. But here's working implementation that looks like the one in lifelines and will do left-censoring: https://gist.github.com/CamDavidsonPilon/02f75791d4cc6e780b561571e9a62037 Let me know if you have trouble with that.

2. Use restriced-mean-survival-time (RMST). This is another successor to the log-rank test, and also only uses the survival function. *lifelines* has support for RMST, [docs here](https://lifelines.readthedocs.io/en/latest/Examples.html#restricted-mean-survival-times-rmst), but not for a formal statistical test, unfortunately.

**Comment by mikekoss** [comment]
@CamDavidsonPilon Thanks so much for your help!  And so quickly.  I was able to use your example 1.  I really appreciate it.  We have a survival analysis package for astronomy, but it's very painful to deal with Fortan, and was never ported completely to python.  [http://articles.adsabs.harvard.edu/pdf/1985ApJ...293..192F](url).  It's great to have a package in python!  I really appreciate the hard work putting this package together.  Will cite the package in the research article.

**Comment by CamDavidsonPilon** [comment]
Thanks for the kind words! Seeing these issues helps me know what's missing from lifelines, so I appreciate you reaching out and making an issue.

**Comment by CamDavidsonPilon** [comment]
I just released v0.25.3, which offers a new API for `lifelines.utils.survival_difference_at_fixed_point_in_time_test` that can handle left-censored data (see example [here](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/tests/test_statistics.py#L513))

**Comment by ErikOsinga** [comment]
Hi,

I am also using lifelines for an astronomical publication, where we have upper limits in the case of non-detections (i.e. left-censored data). 

I would also like to compare two populations statistically, but I'm unsure of how to use the `survival_difference_at_fixed_point_in_time_test`() here. 

In my case, I am using the lifelines package to calculate the Kaplan-Meier estimate of the survival function in different bins of radius (denoted by r/r500), separately for two different populations of sources. I then plot the median depolarisation (denoted by DP) from the survival function using `.median_survival_time_`

This gives a plot like this: 

![DP_vs_rnorm_source_z](https://user-images.githubusercontent.com/12582441/167883654-889f7345-2518-412b-892a-0c9affa9afce.png)

And now I'd like to do a statistical test to test whether these two populations are significantly different or not.

One thing I tried was comparing the survival function of the two populations without binning in radius:

![image](https://user-images.githubusercontent.com/12582441/167885274-02189a97-f458-4e19-bb4e-936b755fb6cc.png)

I could do this using the  `survival_difference_at_fixed_point_in_time_test`(), but I wonder what value of 'time' (or in my case DP) then makes sense to input to this function?

(I also played around with the CoxPHFitter a bit, but it is hard to say how well it is fitting my data because left-censoring is not supported very much yet.) 

Could you help me perhaps? 

Thanks in advance (also for this great software),
Erik

**Comment by CamDavidsonPilon** [comment]
Hi @ErikOsinga, 

I can offer a suggestion or two, but I'm not familiar enough with astronomical data to feel confident in my answer.

> I could do this using the survival_difference_at_fixed_point_in_time_test(), but I wonder what value of 'time' (or in my case DP) then makes sense to input to this function?

This would be domain dependent. In clinical studies of N years, often the end of each year is used. In your case, there many be a better value (any DP between 0 and 1, inclusive).

Another option, instead of comparing medians at a point in time, is the restricted-mean-survival-time. In your case, it would be the difference in area under the curve of the two curves. This is available in lifelines, too.

**Comment by ErikOsinga** [comment]
Thanks for the response @CamDavidsonPilon. I had indeed found the documentation regarding the restricted mean survival time, but I thought that a statistical test was not implemented, but perhaps I just missed something?

**Comment by CamDavidsonPilon** [comment]
Hm, you're right: I don't think I've added a statistical test for it. https://github.com/CamDavidsonPilon/lifelines/blob/bb0561aefb5b1e2b8303ddd38be9a96ca474cc1e/lifelines/statistics.py#L671
