### ISSUE TITLE
How to save/serialize model: WeibulAFTFitter

### ISSUE THREAD

**Issue by torresxavier** [CamDavidsonPilon/lifelines#1138]
Hi there! Nice library this one! I have trained a model using WeibullAFTFitter and would like to reuse it without training it again... I've tried with the suggestions given in the documentation (pickle, dill, and also joblib...) but it keeps on throwing the same mistake: 

" Sorry, pickling not yet supported. See https://github.com/pydata/patsy/issues/26 if you want to help."

If I try with the CoxPH model it works, but not under the WeibullAFTFitter. And the last one is the one showing best performance so I need to save it to disk.

Any thoughts on how to save/serialize a trained WeibullAFTFitter model for future usage?

Thanks

**Comment by CamDavidsonPilon** [comment]
Hi @torresxavier, there was a recent regression in the latest lifelines: in order to support formulas (which, I am guessing you are using), we had to sacrifice some serialization. However, a solution is coming soon, in #1131 - should only be a few weeks. 

If you are comfortable with `pip`, you can do `pip install https://github.com/CamDavidsonPilon/lifelines/archive/try-formulaic.zip` to install a working *lifelines* with full support for serialization.

**Comment by torresxavier** [comment]
I'll check that. Thanks @CamDavidsonPilon !!!

**Comment by CamDavidsonPilon** [comment]
This is now native in lifelines
