### ISSUE TITLE
Cannot match the results of KaplanMeier and Nelson Aalen by hand

### ISSUE THREAD

**Issue by naenumtou** [CamDavidsonPilon/lifelines#1376]
I have fitted both models by using lifelines python library. The results of .event_table from both models are identically matched. However, when I try to recalculate .cumulative_density_ from KaplanMeierFitter() and .cumulative_hazard_ from NelsonAalenFitter(), the results cannot be matched.

![image](https://user-images.githubusercontent.com/66057952/147679545-1df46130-8627-47e1-8452-599472165193.png)

I have used the above formula for cumulative density.

![image](https://user-images.githubusercontent.com/66057952/147679555-b51b3c90-059e-4892-9a7f-0b7e9ebf57e2.png)

I have used the above formula for cumulative hazard.

I also add the data table results from the fitting for the consideration.

![image](https://user-images.githubusercontent.com/66057952/147679591-642bb384-c218-4f6d-be7f-935848d2b926.png)

**Comment by pzivich** [comment]
Hi @naenumtou 

Kaplan-Meier and Nelson-Aalen are distinct estimators that are not strictly equal to each other for finite samples (with the KM being the nonparametric estimator of the survival, and NA being the nonparametric estimator of the cumulative hazard). The two estimators are only equal asymptotically (Nelson W. Theory and applications of hazard plotting for censored failure data. _Technometrics_. 1972;14:945–965)

The small difference between the two estimators is not unexpected.

**Comment by naenumtou** [comment]
Hi @pzivich 

I am not expecting the two values will be equal but what I confuse is why the values (say cumulative density) is not equal when recalculate by the given formula?

**Comment by naenumtou** [comment]
Hi @pzivich

I am not expecting the two values will be equal but what I confuse is why the values (say cumulative density) is not equal when recalculate by the given formula?

**Comment by pzivich** [comment]
Which are your by-hand calculations and which are from lifelines?

Also where is your first formula coming from? That does not correspond to either the KM or NA estimators

**Comment by naenumtou** [comment]
Please find the comparison per image below:
![image](https://user-images.githubusercontent.com/66057952/147760902-46c343b6-81e2-4362-9bd4-21f9495b1076.png)

I followed the formula in the reference links below:
Cumulative density: https://www.kdnuggets.com/2020/07/guide-survival-analysis-python-part-2.html
Cumulative hazard: https://en.wikipedia.org/wiki/Nelson%E2%80%93Aalen_estimator

Please tell me if I did anything wrong. Thanks

**Comment by pzivich** [comment]
Okay, so you aren't matching `KaplanMeier.cumulative_density_` because you seem to be using a different formula. The Kaplan-Meier estimator is not what was written above. It is 
![image](https://user-images.githubusercontent.com/32672909/147794541-813aa83e-c11a-4e87-ad3c-42915aea3783.png)
However, you need to convert to the density. That is done via
![image](https://user-images.githubusercontent.com/32672909/147794621-169a383c-0f53-49c4-9a3d-960318ae4d5c.png)

It also looks like the `.cumulative_hazard_` is being pulled from the Kaplan-Meier and not the Nelson-Aalen estimator. I would double-check that

Below is my by-hand table. My Kaplan-Meier C-density and Hazard both match the lifelines output for your example.
![image](https://user-images.githubusercontent.com/32672909/147794744-b9801907-5d21-4b1b-bd03-17bb9a56f392.png)

You also need to keep relations like the following in mind. They are often used to convert between the different survival parameters between the estimators. For example, the relation between the cumulative density (F(t)) and survival (S(t)) was used above with the Kaplan-Meier estimator
![image](https://user-images.githubusercontent.com/32672909/147794870-fe183256-c159-484a-be10-120d20fda009.png)

**Comment by naenumtou** [comment]
Thanks for the investigating. I am a little bit confuse when you said using different formula.
If doing so, how the number in the reference link (https://www.kdnuggets.com/2020/07/guide-survival-analysis-python-part-2.html) can be match?

**Comment by pzivich** [comment]
I'm not sure why the link above matches, but their formula is wrong. That formula is not how the cumulative density is calculated via the Kaplan-Meier

**Comment by naenumtou** [comment]
@pzivich Thank you, really appreciate.
