### ISSUE TITLE
KaplanMeierFitter raises NotImplementedError for plot_hazard and plot_cumulative_hazard

### ISSUE THREAD

**Issue by HawkiesZA** [CamDavidsonPilon/lifelines#1478]
Using `plot_hazard` or `plot_cumulative_hazard` on the KaplanMeierFitter raises an error and says to use the NelsonAalenFitter or other parametric model. Why is this not possible on the KaplanMeierFitter?

**Comment by CamDavidsonPilon** [comment]
Hi @HawkiesZA, because the Kaplan Meier estimator is the wrong tool for estimating the cumulative hazard. It's efficient at estimating the survival curve. For estimating the cum. hazard, the Nelson Aalen estimator is better. (Of course, you can "cheat" and just apply `-log` to the KM survival curve to get an estimate of the cum. hazard, too)

**Comment by HawkiesZA** [comment]
While I understand that one thing might be better than another, but that doesn't mean it should be excluded as a possibility for ever being used. The API should allow for it and the documentation should reflect that a better way might be possible using a different method.

If you're using KM for survival and then also want the hazard then you should be able to, otherwise you're mixing your methods. At the very least you should then be able to use both and compare them.

**Comment by CamDavidsonPilon** [comment]
I suppose this is decided by where lifelines falls _opinionated_ vs _less-opinionated_ software spectrum. I tend to lean towards opinionated, especially when it comes to statistical software. I don't the API will change here, unfortunately.
