### ISSUE TITLE
Why are the beta parameters slightly off in the coxph model vs R's survival?

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#272]

**Comment by CamDavidsonPilon** [comment]
hmmm, I added a test to compare, and it looks fine. https://github.com/CamDavidsonPilon/lifelines/commit/6a952516c6a099c1d471985ae9b0f569f7e49b66#diff-d313c86d6de32bd872f4e5faf183e438R835

So I think it's something else...

**Comment by CamDavidsonPilon** [comment]
well there are still differences at the 4th decimal place, so I'll reopen this. This still might be the issue of the original problem in the strata baseline survival rates.

**Comment by IvanBarrientos** [comment]
The issue may also be independent of strata since there are small differences in R vs Lifelines betas, with or without strata. It may simply go back to minor differences in newton-rhapson/convergence implementations.

For example, using R (platform x86, version 3.2.2) vs Lifelines (version 0.8.0.2), normalize=False, ties=Efron, time=week, event=arrest, features=fin, age, wexp, mar, paro, prio, and strata=race (in second case):

**Without Strata**
R
coxph(formula=Surv(week, arrest)~fin + age + wexp + mar + paro + prio, data=rossi)
fin  -0.36554
age  -0.05633
wexp -0.15699
mar  -0.47130
paro -0.07792
prio  0.08966

Lifelines (here the 'race' column is deleted from a copy of the rossi data set)
cph = CPH(normalize=False)
cph.fit(rossi_del_race, duration_col='week', event_col='arrest')
cph.summary.coef
fin    -0.365069
age    -0.056131
wexp   -0.158322
mar    -0.470425
paro   -0.077845
prio    0.089264

We can already see (small) differences here.

**With Strata=race**
R:
coxph(formula=Surv(week, arrest)~fin + age + wexp + mar + paro + prio + strata(race), data=rossi)
fin  -0.37877
age  -0.05764
wexp -0.14275
mar  -0.43882
paro -0.08576
prio  0.09221

Lifelines:
cph = CPH(normalize=False)
cph.fit(rossi, duration_col='week', event_col='arrest', strata='race')
cph.summary.coef
fin    -0.377465
age    -0.057306
wexp   -0.143465
mar    -0.441940
paro   -0.083862
prio    0.091875

Finally, when calling cph.baseline_cumulative_hazard_ in Lifelines for this second example with strata=race, it seems there is still only one set of hazards as opposed to R's basehaz() which produces two sets of hazards (one for race=0 and one for race=1). This difference may also have an impact in producing unequal betas in R vs Lifelines.

**Comment by CamDavidsonPilon** [comment]
This was due to a python integer division error. In the latest (to-be-released) 0.13, we are now accurate to at least 4 decimals places: 
https://github.com/CamDavidsonPilon/lifelines/pull/370/files#diff-d313c86d6de32bd872f4e5faf183e438R920
