### ISSUE TITLE
plotting utilities for cox PH?

### ISSUE THREAD

**Issue by disimone** [CamDavidsonPilon/lifelines#284]
Hi,

first of all, thanks for this very nice package.

Sorry if I post this here, but I don't know what a better forum may be. I wanted to ask if there are plans to add, in some future version, plotting capabilities to the Cox model (like I see there are for the Aalen model). 

If some extra explanations are given to me or added to the docs, so that I can produce the plots myself, I would also be glad to contribute my code back to you.

Thanks for your help,

Andrea.

**Comment by CamDavidsonPilon** [comment]
Hi there! Good suggestion. I'm very open to this idea, do you have any plot examples in mind?

**Comment by disimone** [comment]
Hi,

thanks for the reply. I see I can already plot relatively easily the baseline quantities, but I found no easy way to get, for example, the 95% band like in AA or even KM. Is this because of some basic limitation of the model? I think some kind of error band is the very basic addition to make the code usable for presentations.

On top of that, it would be very nice to have, for categorical variables, the specific curves. Like you show in the example for AAF. 

In addtions, for both Aalen and Cox, I think there is something I am missing. I can easily  obtain the baseline, but this should be just the b_0(t), right? How do I get a plot of the full hazard/survival, including all coefficients, on the training data? I guess this would be quite similar to what one gets from KM, but the regularization options in the regression may actually make things interesting. Also, comparing the total result on the training set with the simple KM estimate can certainly help in understanding strange features of the curves.

Off the top of my head, this is all I can think of for the moment :)

What do you think?

Andrea.

**Comment by CamDavidsonPilon** [comment]
Two ideas:

<img width="618" alt="screen shot 2017-04-16 at 22 30 18" src="https://cloud.githubusercontent.com/assets/884032/25077038/506ddf58-22f4-11e7-956b-1ee95066daba.png">
<img width="819" alt="screen shot 2017-04-16 at 22 20 48" src="https://cloud.githubusercontent.com/assets/884032/25077037/506d9732-22f4-11e7-98a4-642cdf4a0471.png">


I don't know which is more popular, but I do like this idea.

> In addition, for both Aalen and Cox, I think there is something I am missing. I can easily obtain the baseline, but this should be just the b_0(t), right? How do I get a plot of the full hazard/survival, including all coefficients, on the training data? 

Cox: because the model is semi-parametric, there is not a definition of a full survival. What you can do to get a "basic" survival plot is to average all your training data over the columns, and run the `predict_survival_function` on new data point.

AAF: Again, there is not really a full survival curve absent any specific data point, however the above technique would work for AAF too.

**Comment by disimone** [comment]
Hi,

thanks for the two plots, and for the explanations. I do like the colored bars more than the first one, but both are indeed very useful.

Andrea.

**Comment by CamDavidsonPilon** [comment]
Added in #298
