### ISSUE TITLE
AalenAdditiveFitter predict_survival_function not decreasing

### ISSUE THREAD

**Issue by TeaPearce** [CamDavidsonPilon/lifelines#285]
Hi, I'm seeing some odd behaviour on the predicted survival functions for the AalenAdditiveFitter... survival curves should never increase right? I know the page says these are still experimental, thought I'd flag it.

```
aaf = AalenAdditiveFitter(fit_intercept=False)
aaf.fit(df_surv_train, 't_rfs', event_col='e_rfs')
aaf.predict_survival_function(df_surv_train_val.ix[0:10]).plot()
```

![lifelines_aaf_plot](https://cloud.githubusercontent.com/assets/25795223/24924794/e50897c6-1eed-11e7-9475-0948089b9ad8.png)

**Comment by CamDavidsonPilon** [comment]
Hey @TeaPearce, this is expected in practice. The hazard function is an unconstrained linear model, which could increase or decrease, and due to sampling/estimation errors, could become negative! If this happens, the survival function will increase. 

In a perfect world, with infinite data, this would not happen. But of course, with finite data, this will happen in practice. There's not much you can do about it - maybe try to stay in the hazard space where for analysis? Or, replace the negative values to be 0 instead. 

Thanks for the comment!
