### ISSUE TITLE
survival function increasing with Aalen’s additive hazard model

### ISSUE THREAD

**Issue by baharian** [CamDavidsonPilon/lifelines#317]
Using AalenAdditiveFitter(), I get predicted survival functions that are increasing (sometimes over very large time spans), which violates a basic assumption of survival analysis. You can probably see a hint of this behavior in [this page](https://lifelines.readthedocs.io/en/latest/Quickstart.html) in [this picture](https://lifelines.readthedocs.io/en/latest/_images/quickstart_predict_aaf.png). The same dataset with CoxPHFitter() leads to predicted survival functions which are non-increasing at all times.
Is there a reason for this behavior of AalenAdditiveFitter()?

**Comment by CamDavidsonPilon** [comment]
Hey @baharian, good question. I should add this to the docs. Based on the model itself, it is possible to have increasing survival functions. This is because the model is so non-parametric, that this condition is not enforced. A practitioner should see these as an artifact of the choice of model. 

Aside from a few gotchas, inference can continue as usual (it's comparable to a curve fitting exercise - things may wiggle around but the gist of the results are correct).

**Comment by baharian** [comment]
Thanks for the reply. For future reference, I found these two papers that discuss this issue:
1) Grønnesby and Borgan, A Method for Checking Regression Models in Survival Analysis Based on the Risk Score, Lifetime Data Analysis 2, 315-328 (1996).
2) Aalen and Scheike, Aalen's Additive Regression Model, Wiley StatsRef: Statistics Reference Online (2014).
