### ISSUE TITLE
Log-rank test and Breslow (Generalized Wilcoxon)

### ISSUE THREAD

**Issue by yong27** [CamDavidsonPilon/lifelines#452]
Thanks for great project!

I'm fan of Lifelines. I'm usually doing log-rank test for two groups. 

In SPSS, there are 3 kinds of test (Log Rank, Breslow (Generalized Wilcoxon), Tarone-Ware) and each description is as follows.

* Log Rank: A test for comparing the equality of survival distributions. All time points are weighted equally in this test.
* Breslow: A test for comparing the equality of survival distributions. Time points are weighted by the number of cases at risk at each time points.
* Tarone-Ware: A test for comparing the equality of survival distributions. Time points are weighted by the square root of the number of cases at risk at each time point.

It seems to easy to implement other tests because of good code quality of lifelines. But I failed to get the same p-value with SPSS.

How can I implement these tests?

Thank you.

**Comment by CamDavidsonPilon** [comment]
Hey @yong27, thanks for the issue. 

Are you saying that the `utils. logrank_test` in lifelines produced different results from SPSS? As for the other two tests, no, those don't exist yet. Those seem like good additions though.

**Comment by sean-reed** [comment]
I had a go at adding the Wilcoxon and Tarone-Ware test stats: https://github.com/sean-reed/lifelines/blob/bb93312c4462c5a808118a6f1b79ea76aab2a9f7/lifelines/statistics.py#L649

Not much to the implementation of the tests themselves since just a case of applying weightings in the numerator and covariance matrix computations within the existing log-rank statistic implementation - mostly a refactoring to avoid duplicated code between the test statsistics. I still need to add some unit tests but were correct on on a few test examples I tried...

**Comment by sean-reed** [comment]
There are a few other popular variations on the log-rank test that could also be added such as Peto and Flemington-Harrington.

**Comment by CamDavidsonPilon** [comment]
:+1: that's a nice refactor, @sean-reed - happy to merge changes like those in

**Comment by sean-reed** [comment]
Great, I will add the other log-rank test variants and the unit tests etc. soon.
