### ISSUE TITLE
Overflow encountered in long_scalars

### ISSUE THREAD

**Issue by mcbuch** [CamDavidsonPilon/lifelines#507]
I've been trying to fit a CoxPHFitter on a dataset of 100.000 observations and about 15 variables (including the event- and duration columns), but I get the following warning:

```
C:\Anaconda\lib\site-packages\lifelines\utils\__init__.py:948: RuntimeWarning: overflow encountered in long_scalars
num_tied += tied
```

I've tried removing columns one by one to check for data inconsistencies, and also different transformations of variables (rounding floats, float to integer, checking for characters in numeric columns) to no avail. The samples are selected at random from a larger set of observations. 

What does work is reducing the number of observations to 78.000 (78.500 fails). After delving into the overflow issue, for example [here](https://stackoverflow.com/questions/7559595/python-runtimewarning-overflow-encountered-in-long-scalars), it seems that the num_tied is of dtype int32, and the warning is raised when the number excedes 2147483647. The fix could/should be to declare the variable like this:

`    num_tied = np.int64(0)`

Something to considere in a future update?

**Comment by CamDavidsonPilon** [comment]
This is a simple fix - thanks for raising this. 

(aside: I'm surprised your dataset manages to have `num_tied` exceed 2147483647!)

**Comment by jamesmckownbishop** [comment]
I can produce this issue for num_correct instead of num_tied:

`
from lifelines.utils import concordance_index
import numpy as np

a = np.arange(65536)
concordance_index(a, a) # Returns 1.0 as expected

b = np.arange(65537)
concordance_index(b, b) # Should return 1.0 but instead returns -0.999...
concordance_index(b, b[::-1]) # Returns 0.0 as expected
`

num_ties issue indeed appears to be resolved:

`
c = np.zeros(65538)
c[0] = 1
concordance_index(c, c) # Returns 1.0 as expected
`

**Comment by CamDavidsonPilon** [comment]
!! thanks for sharing this! 

I added some changes in v0.15.0 (https://github.com/CamDavidsonPilon/lifelines/pull/496/files#diff-81aff105858474f333c6fc40c9edae5eR904) but haven't been able to test the changes because I couldn't reproduce the error!
