### ISSUE TITLE
Weibull fitter: delta nan error

### ISSUE THREAD

**Issue by hcarlens** [CamDavidsonPilon/lifelines#533]
Hi Cam/lifelines contributors,

Thanks for this great package. 

I'm trying to use the Weibull fitter, mostly successfully, but I get an error when using this data set: 

```
from lifelines import WeibullFitter
T = [13467, 13760, 12011, 7798, 7928]
E = [0,1,0,0,0]
wf = WeibullFitter()
wf.fit(T, E)
```

This is the full error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-4b49a1327419> in <module>
      3 E = [0,1,0,0,0]
      4 wf = WeibullFitter()
----> 5 wf.fit(T, E)

c:\users\hcarlens\appdata\local\continuum\anaconda3\envs\lab\lib\site-packages\lifelines\fitters\weibull_fitter.py in fit(self, durations, event_observed, timeline, entry, label, alpha, ci_labels)
     99 
    100         # estimation
--> 101         self.lambda_, self.rho_ = self._newton_rhaphson(self.durations, self.event_observed)
    102         self.survival_function_ = pd.DataFrame(self.survival_function_at_times(self.timeline), columns=[self._label], index=self.timeline)
    103         self.hazard_ = pd.DataFrame(self.hazard_at_times(self.timeline), columns=[self._label], index=self.timeline)

c:\users\hcarlens\appdata\local\continuum\anaconda3\envs\lab\lib\site-packages\lifelines\fitters\weibull_fitter.py in _newton_rhaphson(self, T, E, precision)
    151             delta = solve(j, - step_size * g.T)
    152             if np.any(np.isnan(delta)):
--> 153                 raise ValueError("delta contains nan value(s). Convergence halted.")
    154 
    155             parameters += delta

ValueError: delta contains nan value(s). Convergence halted.
```

I'm using Python 3.6.6, and lifelines 0.14.6. Could you help me understand what's going wrong here? Is this a limitation in the library, or an issue with the data set? Is this something I can check for before running the fitter? 

Granted, the usefulness or meaning of the 'fit' in this specific case is debatable, but it would still be good to know why it's failing.

**Comment by pzivich** [comment]
There is only one event in the data provided. The Weibull fitter can't converge to this single event. As an example, I switched the code to ``E = [0, 1, 0, 0, 1]`` and the model converged.

This is not an issue with lifelines but is more related to the data set. There isn't enough observations for the Weibull model to be estimated

**Comment by CamDavidsonPilon** [comment]
I made some covergence improvements in v0.15 (not released yet), let me try this dataset there

**Comment by hcarlens** [comment]
FYI - I debugged one of my other data sets and found that this error was occurring because some of the values I was passing in `durations` were `inf` due to overflows upstream. 

It might be useful to add an explicit check and error message for inf values, to help anyone who makes the same mistake as me! (or I'd be happy to have a go at this on the v0.15 branch if you think this is a good idea)

**Comment by CamDavidsonPilon** [comment]
That's a good idea - you can add a similar check to https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/fitters/weibull_fitter.py#L86, even better, change the function of `check_nans` to `check_nans_or_infs` 

Located here: https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/utils/__init__.py#L1089 and used in many places.

Happy to accept a PR for v0.15.0!

**Comment by CamDavidsonPilon** [comment]
> Thanks, but there seems to be more to it than that. For example, if I change the code to E = [0,0,1,0,0], the fitter also returns a result. I also have some larger data sets where I'm seeing this issue, but I figured I'd share the simplest example!

So this doesn't really work in the traditional sense either - the iterations do halt but it halts because it exceeds the max iterations (I've added a warning for this just now). So it doesn't really _converge_.

**Comment by hcarlens** [comment]
@pzivich thanks so much for the explanation! It seems obvious now that you present it like that. Is there a set minimum number of observations required for a Weibull fitter to converge, or does it depend on the data? (I'm trying to see if there are some checks I can run on my data before trying to fit)

**Comment by pzivich** [comment]
No problem @hcarlens . Glad to help! As for the number of observations, I am unaware of any heuristic for the number of observations for a Weibull model. As always, the more events to fit the model to the better. Realistically, Weibull models can fit to a few observations fairly well since only two parameters are estimated. However, this depends on the variance of the data (large variation may not allow good model fit to only a few events).

One good practice is to check your Weibull model by first estimating the survival distribution non-parametrically via Kaplan Meier (``KaplanMeierFitter`` in lifelines). First plot the survival curve to make sure it has some general shape that makes sense (no large drop offs or other oddities). Afterwards you can use the ``plot_loglogs()`` function within ``KaplanMeierFitter`` to generate a log-log plot. In this plot, you are looking for a straight line relationship between the X-Y axes. If there is, that suggests the Weibull model is a good parametric model choice. If it isn't you would want to use another parametric model or use non-parametric methods like Kaplan Meier.

Below is some sample code you can adapt to your purpose

```
from lifelines import KaplanMeierFitter
import matplotlib.pyplot as plt

# Fitting Kaplan Meier
km = KaplanMeierFitter()
km.fit(durations=df['T'], event_observed=df['E'])

# Plotting survival curve
km.plot()
plt.show()

# Plot log-log transformed survival curve
km.plot_loglogs()
plt.show()
```
