### ISSUE TITLE
[hazard ratio for a specific variable]

### ISSUE THREAD

**Issue by vatn** [CamDavidsonPilon/lifelines#620]
Hello, 

I want to know : if i have a categorical variable like sexe(male or female or global ), with using  CoxPHFitter, is that possible to get hazard ration of male versus global or female versus global ? 

Thank you so much ! 

Tian

**Comment by CamDavidsonPilon** [comment]
Hi Tian, can you describe what you mean by "versus global"?

**Comment by CamDavidsonPilon** [comment]
Hm, how is someone of Global gender?

**Comment by jojordan3** [comment]
@vatn, by "Global" do you just mean the something like the "average" individual? Global in this case just meaning to represent the entire population?

e.x. instead of just being able to say female has twice the risk of death of male, being able to say female has 1.3 times the average risk while male has .7 times the average risk?

If your male-female ratio is 1:1, this is fairly trivial to do mathematically, but if not, and/or if you have > 1 variable I can see how things might get interesting (maybe--I'll have to think about it more). 

If this is what you mean, I'd love to take a look and see if it's worth doing, and try to integrate something after some further discussion with @CamDavidsonPilon

**Comment by vatn** [comment]
@jojordan3 , Thank you much for the reply ! :+1: !
Yes, it is exactly what I mean. 
For Global, I want to compute a survival probalibility P(global) based on the entire population. Then I  also compute the probabilities for female and male. 
For example, if i code the sexe as the following and sexe is the only predictor in my model : 
Global -> 0
Female - > 1
male -> 2
And I want the model to consider automatically Global as the baseline of which Xbeta = 1. (because I code global as 0).
If female-global ration is 5:1,  
if for certain age, i don't have enough population(expositions) for female to estimate the survival probability, I can apply the formula  probability (Female) = probability of baseline ** (ratio female-baseline) = probability of Global ** (ratio female-Global) .

I hope my explanation is clear, I just use the SAS, PROC PHREG before, in this model, it will always consider certain categories (such as Global in this case) as baseline (of which Xbeta =0 and expo(Xbeta)=1).
I try to read your codes, I have seen that you do the normalization of the variables, I try to get the same result as SAS, but I didn't succeed to do it.

Thank you much ! 
Tian

**Comment by jojordan3** [comment]
@vatn , can you give me an example of what the input data might be for this use case? --Do you literally have some individuals with gender = Global? or do you have everyone labeled as male and female and just want this additional feature? ...
