### ISSUE TITLE
Smarter initializations for AFT models

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#664]
Related to #661, we can choose better initial values for AFT models. 

From flexsurvreg:

> If not specified, default initial values are chosen from a simple summary of the
survival or censoring times, for example the mean is often used to initialize scale
parameters. See the object flexsurv.dists for the exact methods used. If the
likelihood surface may be uneven, it is advised to run the optimisation starting
from various different initial values to ensure convergence to the true global
maximum.

**Comment by CamDavidsonPilon** [comment]
Strategy: under the null (or even averaging over all scenarios), all the coefficients are nil and the intercepts are equal to the values fitted in a univariate parametric model. Thus good default values for the intercepts are  values fitted in a univariate parametric model. This comes at a perf cost, but we make it up later as we cache the null log likelihood for the log-likelihood ratio test.

**Comment by CamDavidsonPilon** [comment]
We also may gain performance on less iterations 🤞

**Comment by bacalfa** [comment]
Nice! Yes, a smarter initialization might be useful for robustness, as long as it doesn't significantly degrade performance (maybe it should be optionally activated?). It may be the case that a user already applies a problem-specific strategy to handle convergence issues, so forcing a robust, but slow approach for each call to `.fit` wouldn't be very welcome in this case.

Multi-start can be a good idea (since we're dealing with a nonlinear optimization problem), but I wouldn't affirm something like 

> to ensure convergence to the true global maximum.

because we're not applying a deterministic optimization algorithm to provably converge to the global solution.

**Comment by CamDavidsonPilon** [comment]
From my local performance tests, it won't be noticeable (and you can always "turn it off" by supplying values like `np.zeros(..)`). 

I'm surprised they use multi start. Unless I'm missing something, the log-likelihood is non-linear _but_ is convex, so optimization algos should converge to the global minimum. 

Part of the my problem is I can't get the model to actually fail to converge, so it's hard to know what needs to be done.

**Comment by bacalfa** [comment]
Equation 20 on page 5: https://www.biorxiv.org/content/biorxiv/early/2018/08/27/362186.full.pdf. I don't think we're dealing with a convex model here. We wouldn't need a starting point if it were convex (just enough iterations).

**Comment by CamDavidsonPilon** [comment]
Yea, you're right: the proof is in the pudding. Different results for survreg vs flexsurvreg vs lifelines suggest local minima.
