### ISSUE TITLE
Cox Proportional Hazard Model One hot encoding

### ISSUE THREAD

**Issue by tom-hao** [CamDavidsonPilon/lifelines#692]
If I one hot encode a variable, how can I structure it so that the model understands that the new group of binary columns are related? Is it possible to feed data like this [0, 0, 1], [1, 0, 0] into the model?

**Comment by CamDavidsonPilon** [comment]
hi @tom-hao, 

If I understand your question, then yes, the one-hot format encodes that the columns are related, and this can be provided to lifelines. However, because of the linear combination of the three variables, you'll need to drop one. Ex:

```
X = np.array([
[0, 0],
[1, 0]
])
```

**Comment by tom-hao** [comment]
So do you just use getdummies() or do you merge the dummy columns into one? How does lifelines know that the dummy columns are related?

**Comment by CamDavidsonPilon** [comment]
You just use `get_dummies` - don't merge them into one column. Also don't forget to use `drop_last` in `get_dummies`, or explicitly drop one of the columns. 

I'm curious why you expect / want the model to know those columns are related? I can't think of many linear models where this is explicited implemented (or how).

**Comment by tom-hao** [comment]
I'd like to see the hazard coefficient for the variable that is one hot encoded. If each category in the variable ends up as a separate column, the coxPHfitter ends up creating a hazard coefficient for each category, which is not useful in understanding the hazard of the variable as a whole.

**Comment by CamDavidsonPilon** [comment]
Right, I understand, and I believe Stata reports the p-value associated with the question "this variable is significant w.r.t. this regression". However, I don't think the question you pose can be answered (please feel free to correct me). Consider something like Age, which is _not_ categorical. We can assign a single hazard ratio to Age because there is a) an natural ordering (year 10 < year 11), b) it's linear (year 10 - year 9 == year 9 - year 8), c) and there is a natural baseline to compare everything against (year 0). A covariate that is categorical, like country, fails each of these criteria. 

Similarly, consider something like "the hazard ratio of being from a country is 2.0" - it makes no sense.  However, "the hazard ratio of being from Canada is 2.0" makes sense.
