### ISSUE TITLE
parallelizing the CoxPH fitting process

### ISSUE THREAD

**Issue by hammer-wang** [CamDavidsonPilon/lifelines#745]
Hi,  I'm dealing with very high dimension datasets (~20,000 dimension) with more than two thousands samples. I find that fitting a CoxPH is extremely slow. I'm wondering whether there is any way to speed up this fitting process? For example, can we set number of jobs for parallel computing, just like scikit-learn? 

Thanks!

**Comment by CamDavidsonPilon** [comment]
To directly answer your question about parallelization: no.

Hm, that's tough because it's going to create a 20k x 20k matrix to handle the hessian matrix. This is going to be very expensive. Let me ask a few questions:

1. Do you care about the standard errors, variances, CI, etc. of the covariates?
2. How many ties are in your dataset? Ex: how many unique durations do you see?

**Comment by hammer-wang** [comment]
Hi, thanks a lot for your quick reply! 

1. I do not care about those statistics of the covariates. The only thing I need is the c-index for now.
2. The ratio between the number of unique duration and the total number of uncensored samples is about 0.1.

**Comment by CamDavidsonPilon** [comment]
You may have better results with scikit-survival
