### ISSUE TITLE
score_ -> log_likelihood

### ISSUE THREAD

**Issue by CamDavidsonPilon** [CamDavidsonPilon/lifelines#819]
I'm increasing like using the log-likelihood as a measure of "fit" in sample and out of sample. 

At the moment, a model's `score_` is the c-index, which I'm increasingly _not_ liking. 

I may consider swapping these two...

**Comment by KSafran** [comment]
IMHO this would be a good change.

Related question - why [just do log-likelihood for the uncensored data.](https://github.com/CamDavidsonPilon/lifelines/blob/master/lifelines/metrics.py) Couldn't you also calculate a likelihood for censored data using 1 - CDF? Isn't log-likelihood for uncensored points only biasing the predictions downward (due to sampling bias)?

**Comment by CamDavidsonPilon** [comment]
@KSafran, can you expand a bit more on your question? I am not understanding where in the code the likelihood for censored is not calculated.
