### ISSUE TITLE
Calculating LTV from survival function

### ISSUE THREAD

**Issue by davidgibsonp** [CamDavidsonPilon/lifelines#825]
Hi! Is there a direct way to calculate LTV for a subscription service using the survival function? The function seems very valuable when looking at retention but I am not sure how to get the LTV for say 6 months.

This all I have found is taking the `area under the curve` * `average revenue`.

Thanks!

**Comment by CamDavidsonPilon** [comment]
Hi @davidgibsonp, 

That formula is equal to the the following:

<img width="304" alt="Screen Shot 2019-09-08 at 1 48 06 PM" src="https://user-images.githubusercontent.com/884032/64492177-54dc3100-d23f-11e9-991e-ffb1585705a1.png">

 But we can do much better. Consider that i) we tend to discount future revenue, ii) older customers tend to {purchase more, have a more expensive plan} per month, iii) we want a 6-month LTV, not an infinite time horizon LTV. 

<img width="469" alt="Screen Shot 2019-09-08 at 1 55 47 PM" src="https://user-images.githubusercontent.com/884032/64492285-68d46280-d240-11e9-9ce4-f3259db89ccf.png">


_d_ is a discount rate, like 0.99 or something. E[R_i] is the average _i_th month revenue by customers who lasted atleast _i_ months. This takes care of point i) above. The sum is also finite, so that handles point iii). 

Anyways, lifelines doesn't handle this, you'll need to code it up yourself.
