### ISSUE TITLE
How to use arbitrary censored data in WeibullAFTFitter.fit

### ISSUE THREAD

**Issue by leavor** [CamDavidsonPilon/lifelines#835]
## Versions
* lifelines version: 0.22.3
## Problem Description
There are some life data, including left censored, right censored, interval censored, and non-censored. In WeibullAFTFitter.fit, how to use this set of data, my code is like this:
```Python
import numpy as np
import pandas as pd
from lifelines import WeibullAFTFitter
# '*' represents missing data
startTimeSrc = ['*',2,4,6,8,10,12,14,'*',2,4,6,8,10,12,14,'*',2,4,6,8,10,14,12,11]
endTimeSrc = [2,4,6,8,10,12,14,'*',2,4,6,8,10,12,14,'*',2,4,6,8,10,12,'*',14,11]
event = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]
temperature = [125,125,125,125,125,125,125,125,150,150,150,150,150,150,150,
               150,175,175,175,175,175,175,175,175,175]
# Left censored uses '-np.inf' instead
startTimeAFT = [-np.inf,2,4,6,8,10,12,14,-np.inf,2,4,6,8,10,12,14,-np.inf,2,4,6,8,
             10,14,12,11]
# Left censored uses '0' instead
startTimeAFT0 = [0,2,4,6,8,10,12,14,0,2,4,6,8,10,12,14,0,2,4,6,8,
             10,14,12,11]
# Right censored uses 'np.inf' instead
endTimeAFT = [2,4,6,8,10,12,14,np.inf,2,4,6,8,10,12,14,np.inf,2,4,6,8,10,12,np.inf,
           14,11]
# Raw data set
dfSrc = pd.DataFrame({'startTime':startTimeSrc,'endTime':endTimeSrc,
                      'temp':temperature,'event':event})
# I want to use this dataset but I get an error
dfAFT = pd.DataFrame({'startTime':startTimeAFT,'endTime':endTimeAFT,
                      'temp':temperature,'event':event})
# This data set can be used normally
dfAFT0 = pd.DataFrame({'startTime':startTimeAFT0,'endTime':endTimeAFT,
                      'temp':temperature,'event':event})
aft = WeibullAFTFitter()
# Left censored uses '0' instead, right censored uses 'np.inf' instead, It's OK
aft.fit_interval_censoring(dfAFT0,'startTime','endTime', event_col='event')
aft.print_summary()
# Left censored uses '-np.inf' instead, right censored uses 'np.inf' instead, then error
aft.fit_interval_censoring(dfAFT,'startTime','endTime', event_col='event')
aft.print_summary()
```
The error message is as follows:
<details>
Traceback (most recent call last):

  File "E:/work/Amos/myAlgorithm/统计分析/可靠性_生存/regression_with_life_data_demo.py", line 32, in <module>
    aft.fit_interval_censoring(dfAFT,'startTime','endTime', event_col='event')

  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\lifelines\utils\__init__.py", line 64, in f
    return function(self, *args, **kwargs)

  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\lifelines\fitters\__init__.py", line 2425, in fit_interval_censoring
    entry_col=entry_col,

  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\lifelines\fitters\__init__.py", line 1439, in _fit
    initial_point=initial_point,

  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\lifelines\fitters\__init__.py", line 1486, in _fit_model
    initial_point_dict = self._create_initial_point(Ts, E, entries, weights, Xs)

  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\lifelines\fitters\__init__.py", line 2600, in _create_initial_point
    uni_model.fit_interval_censoring(Ts[0], Ts[1], event_observed=E, entry=entries, weights=weights)

  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\lifelines\utils\__init__.py", line 64, in f
    return function(self, *args, **kwargs)

  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\lifelines\fitters\__init__.py", line 829, in fit_interval_censoring
    utils.check_nans_or_infs(lower_bound)

  File "d:\ProgramData\Anaconda3\envs\python37\lib\site-packages\lifelines\utils\__init__.py", line 1016, in check_nans_or_infs
    raise TypeError("Infs were detected in the dataset. Try using np.isinf to find the problematic values.")

TypeError: Infs were detected in the dataset. Try using np.isinf to find the problematic values.

**Comment by CamDavidsonPilon** [comment]
Hi @leavor, thanks for bringing this up. There are two options:

* Lifelines will error out, as you have seen, when a inf is detected in the lower_bound (`startTime` in your example). When I wrote that, I really was only thinking of positive inf! You have a good point that -inf is valid (but see my point 2 below). I may change this to allow negative lower bounds, specifically -inf. 
* I think you can be more precise in your bounds. Since you are using a Weibull model, you are (implicitly) making the assumption of _positive_ data. Thus any value must be in (0, inf). So using -inf as a lower bound is overkill - you can just use 0. This is why the `dfAFT0` works, but not the `dfAFT`. In your example, you have the subject `('*', 2)`. To my understanding, this could represent:
  - that the subject was born sometime in (0, 2) and when you checked at 2, they were dead. If this is correct, then it's an interval censored subject and you want to set '*' equal to 0. 
  - if `('*', 2)` represents something like "they have been around for a long time, even before me recording, but at time=2, they died" - this is actually a right-censoring problem. Why? Since we don't know how long they lived, but it's _at least_ more than 2 (emphasis on the _at least_, which implies a right censoring problem). So it should be `(2, inf)` in fact. 
  -  if `('*', 2)` represents something like "they have been around for a long time, even before me recording, but at some time in (0, 2), they died", then I think the censoring is interval, with bounds (0, inf) - that is, you can't say anything really about its lifetime. It's still an observation, however. 

Am I missing an interpretation? I guess what I am saying is: do you really have left-censoring? I typically don't see all three censorings mixed (but please let me know if this is indeed that situation!) - typically I see right / interval together.

**Comment by leavor** [comment]
Thank you @CamDavidsonPilon for your answer.
These data are not real data. It comes from a book. The original data is that there is no left censored data. The left censored data is added by myself. I just want to use all the censored type data to do the experiment.
I now know my mistake, the time data is not negative, its minimum value is 0, so the left censor is actually the interval censored at the beginning of 0.
I also did a test in minitab, the result verified this, the minitab test results are as follows:
* **Arbitrary censored type:**
![image](https://user-images.githubusercontent.com/1759365/65208111-9a61ef00-dac6-11e9-923b-5e99bc80b578.png)

* **No left censored, replaced with 0 to start the interval censored:**
![image](https://user-images.githubusercontent.com/1759365/65208353-58857880-dac7-11e9-89c0-ee3a27092b6e.png)

**The data used in minitab is as follows:**
![image](https://user-images.githubusercontent.com/1759365/65209228-072ab880-daca-11e9-94f6-79d44cb52cdd.png)

* **Minitab input interface**
![image](https://user-images.githubusercontent.com/1759365/65209066-82d83580-dac9-11e9-98de-e215238b9519.png)

* **Results of lifelines:** (That is the result of fitting with dfAFT0) 
![B848B218-6335-4ef1-819A-31CE28392228](https://user-images.githubusercontent.com/1759365/65208521-f6794300-dac7-11e9-8b49-14516e193b07.png)

Thanks again!

**Comment by CamDavidsonPilon** [comment]
Glad this was resolved! These are tricky concepts!
