### ISSUE TITLE
Multiple regression where independent and dependent variables are left censored

### ISSUE THREAD

**Issue by RyanConway91** [CamDavidsonPilon/lifelines#879]
I am interested in developing a predictive regression model to use measured concentrations of a suite of compounds to predict the concentrations (or occurrence) of another compound of interest. Both dependent and independent variables are left-censored (contain non-detects). Can this be done in lifelines? If so, what should I be looking at?

**Comment by CamDavidsonPilon** [comment]
Hm, yes I think this can be done. Let me get in front of a computer later and I’ll type a small example out.

**Comment by CamDavidsonPilon** [comment]
Okay, so here's the idea. Because the goal is only prediction, we can focus on 1) correctly modelling the dependent variable's left censorship, 2) feature engineering to circumvent the indep. variable's censorship. 

I'm guessing you have indicators for when each variable has been censored? For the indp. variables, these indicators provide information about the correct (uncensored) value. To be very blunt, let's assume a linear relationship:

```
x_uncensored = beta_1 * idp_x_obs + beta_2 * idp_x_cens
```

This is 100% _wrong_, but let's not care because our goal is prediction accuracy. Putting this altogether, our model is 

```
surv(dep_y_obs, dep_y_cens) ~ 1 +  idp_x1_obs + idp_x1_cens  +  idp_x2_obs + idp_x2_cens  + ...
```

In lifelines, assuming only a single indp. variable:

```python
from lifelines import WeibullAFTFitter # also, LogNormalAFTFitter, and others. See docs. 

df = pd.DataFrame([
 {'dep_y_obs': 1.0, 'dep_y_cens': False,  'idp_x1_obs': 5.0, 'idp_x1_cens': True},
 {'dep_y_obs': 3.0, 'dep_y_cens': True, 'idp_x1_obs': 3.0, 'idp_x1_cens': False},
 {'dep_y_obs': 2.0, 'dep_y_cens': True,  'idp_x1_obs': 2.0, 'idp_x1_cens': False},
 {'dep_y_obs': 2.0, 'dep_y_cens': False, 'idp_x1_obs': 6.0, 'idp_x1_cens': True},
 {'dep_y_obs': 2.5, 'dep_y_cens': True, 'idp_x1_obs': 7.0, 'idp_x1_cens': True},
 {'dep_y_obs': 2.7, 'dep_y_cens': True, 'idp_x1_obs': 8.0, 'idp_x1_cens': True},
])


wf = WeibullAFTFitter()
wf.fit_left_censoring(df, 'dep_y_obs', 'dep_y_cens')
wf.predict_survival_function(df)
```

**Comment by RyanConway91** [comment]
This is great, thanks! Do you know of any papers that may have done something like this I can reference?
I will be interested to try the regressions with, without , and only with the imputations and see how they compare.

**Comment by RyanConway91** [comment]
Once the model has been fit, how would I use it predict the median concentration of the compound of interest given a new set of observations of the independent variable(s)? I tried: 
`m = wf.predict_median(df.loc[1])`
and
`X = df.loc[1,["idp_x1_obs","idp_x1_cens"]]`
`m = wf.predict_median(X)`
But I get errors in both instances

**Comment by CamDavidsonPilon** [comment]
@RyanConway91 looks like you found a bug! To fix this, try casting to a float (and use a dataframe), ex:

```python
m = wf.predict_median(df.loc[[1]].astype(float))
```
