### ISSUE TITLE
plot_lifetimes() / Multicenter Aids Cohort Study Example

### ISSUE THREAD

**Issue by jan-marchant** [CamDavidsonPilon/lifelines#995]
Hi there, thanks for this great resource. I think there's a small issue with the plot_lifetimes() example using Multicenter Aids Cohort Study data given here:

https://lifelines.readthedocs.io/en/latest/Survival%20analysis%20with%20lifelines.html

With recent Pandas the example fails with a KeyError. This is because plot_lifetimes() can only properly handle dataframes with a sequential index starting at 0, and the example data starts at index 1. This doesn't error with Pandas < 1.0 which instead silently drops rows with mismatched indices (as described here: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike')

The solution that works for me is to load the example data with:

df = load_multicenter_aids_cohort_study().reset_index(drop=True)

but I expect a better solution is to reset the index inside plot_lifetimes() so that whatever data is passed is handled properly.

Cheers,
Jan

**Comment by sean-reed** [comment]
Additionally, it doesn't sort by duration correctly when durations argument is a Panda DataSeries. Example:
```
from lifelines.plotting import plot_lifetimes
import pandas as pd

durations = [10, 15, 5, 25, 20]
event_observed = [1, 0, 0, 1, 1] 

df = pd.DataFrame({'durations': durations, 'event_observed': event_observed})

plot_lifetimes(df['durations'], df['event_observed'])
```

**Comment by sean-reed** [comment]
Related to this, would it be better to have the plot bars be labelled by the corresponding indices from the Pandas series instead of 0 to 1? It does this already with the default index but if the index is something like ["Item 1", "Item 2", "Item 3"] instead, then it seems better to have this displayed next to the bars on the y-axis instead of 0, 1, 2. Now would be the ideal time to implement this, since any code using plot_lifetimes with a non-default index currently fails due to the issue raised above and for anything else the output would remain the same. Could also add as an optional parameter like label_by_index=True. Thoughts?

**Comment by CamDavidsonPilon** [comment]
Whoops, sorry @jan-marchant, seems I missed this issue. But luckily @sean-reed is here to help in https://github.com/CamDavidsonPilon/lifelines/pull/1003

@sean-reed your suggestion of using index values is great. Want to implement that in your PR as well?

**Comment by sean-reed** [comment]
Great, I've pushed the update.
